name: DProQ
channels:
  - bioconda
  - pytorch
  - salilab
  - dglteam
  - conda-forge
  - defaults
  - salilab
dependencies:
  - python=3.8
  - pytorch 1.10
  - dgl-cuda11.1
  - torchvision
  - biopython
  - dssp=3.0.0
  - pytorch-lightning
  - scikit-learn
  - pandas
  - joblib
  - cudatoolkit=11.3
  - wandb
  - biopandas